apiVersion: v1
kind: PersistentVolume
metadata:
  name: asset-manager-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/assets"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-manager-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
