apiVersion: v1
kind: PersistentVolume
metadata:
  name: try-on-db-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/try_on_db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: try-on-db-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
